'''Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''
def isPentagon(x):
    if (1 + (1 + 24*x)**0.5) % 6 == 0: # from -b + sqrt(b2 - 4ac)/2a
        return True
    return False

def PentagonNumbers():
    result = True
    i = 1
    while result:
        for j in range(1, i):
            a = i*(3*i - 1)/2
            b = j*(3*j - 1)/2
            if isPentagon(a - b) and isPentagon(a + b):
                result = False
                break
        i += 1
    return a - b

final = PentagonNumbers()
print(final)